### ISSUE TITLE
Program Creation partially works in event of Ego Failure

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/program-service#100]
**Description of Issue** 
When a program is created and some parts fail, you get an error message. However, it appears some data is still being recorded.

**Steps to Reproduce**
1) Shut down ego ( either in qa or locally)
2) Create a program.  you will receive a `ERROR 2: UNKNOWN` message
3) check the database, you will see that the program fields were initialized, but no ego groups were created

**Expected Behaviour**
When a program is created, if certain parts of initialization fail, the whole thing should fail and the point of failure message should be returned.  

- [ ] Need to make sure Ego is promoted to QA first

**Comment by alekspejovic** [comment]
Dusan fixed this issue in another PR.

**Comment by rosibaj** [comment]
Reopening for monitoring - I thought that I saw this issue occuring Aug 7 during testing
