### ISSUE TITLE
Registration email not being sent to program admin on Create Program 

### ISSUE THREAD

**Issue by alekspejovic** [icgc-argo/program-service#107]
**Description of Issue** 
When a program is created, an email is not  being sent to the program admin (email provided in request), to register for the program. 

**Steps to Reproduce**
1) Connect to argo-qa program-service
2) Create a program and provide admin email.  Program should be created succesfully.
3) Check mailhog to see whether email was sent. 

**Expected Behaviour**
When a program is created, an email should be sent to the program admin.

**Comment by Buwujiu** [comment]
Sending registration email when creating a program was not implemented in `createProgram` endpoint. what has been done in this ticket include: 
1. sending email to admin email address
2. removing join admin users logic from `createProgram`
