### ISSUE TITLE
Update User accepts incorrect role codes

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/program-service#110]
**Describe the bug**
When an incorrect user role code is provided, the update user request still goes through and defaults the user to collaborator status. 

**Steps To Reproduce**
Steps to reproduce the behaviour:
1. Go to update Users
2. Add in all the fields, but include  a garbage role code (55 or 11) 
3. You can see that you get a success message and the user gets assigned collaborator status. 
**Expected behaviour**
If a garbage role code is provided, and error should be sent back that it is not accpeted. 

The users status should not change at all on an unsuccessful update.

**Comment by Buwujiu** [comment]
As discussed, this is not a code issue, BloomRPC converts all invalid enum user role values to default value 0(Collaborator). Tested update user endpoint using grpcli and got expected error results. Closing the ticket.
