### ISSUE TITLE
Ability to retrieve invitations

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/program-service#122]
Currently, the UI plans to list all users for a program, including users that are just invited: 
![image](https://user-images.githubusercontent.com/15824252/60206792-72922080-9822-11e9-8f4a-bd414713d626.png)

In this example, the User name, email Role, Invitation Status and Joined date need to be available.  Right now, this information is not retrievable from the Program-Service. 

We need a way to access the invitation status of all of the invitations for a program.  

For the downstream services, the preference would be to be to 
1) list all users in `List Users` (i.e including only invited users) and 

2) include  `Invite status` and `join date` in `List Users`

For each UNIQUE (based on email)  user in a program
- The `status` should be NULL, PENDING, EXPIRED, or ACCEPTED
- - Null means they didn't have an invite and were added directly in EGO-UI
-- in this case, `accepted_at` should be null.
-- PENDING means there is an active invitation
-- EXPIRED means there is an active invitation that expires
-- ACCEPTED means there is an active invitation that the user successfully joined with.

NOTE: This assumes that each program/email combo has  only one invitation at a time.
In case of multiple invites:
- if there is an accepted invitation that should be considered the most accurate
- If there are multiple accepted invite, then the most recent one should be considered accurate.
- If there are multiple un-accepted invites, the most recent pending invitation should be considered the most accurate.

-----
Out of scope issues that need to be handled in other tickets to ensure the assumption that there is only one invitation/user.
- Re-inviting a user should REPLACE any invitations that exist for that user (not add).  Per unique program/email, there should only be one active invitation.
- Removing a user should remove any invitations.

**Comment by rosibaj** [comment]
@alekspejovic I've added this to the next sprint as its a blocker for listing users from the UI

**Comment by hlminh2000** [comment]
one question: is this the same relationship that is needed for this? https://github.com/icgc-argo/argo-platform/issues/189

From a Graphql's perspective, would be great if we could achieve a schema that looks something like so:
```graphql
enum ProgramUserRole {
  # whatever values here
}

enum ProgramUserStatus {
  # whatever values here
}

type ProgramUser {
  name: String
  email: String
  role: ProgramUserRole
  dacoApproved: Boolean
  status: ProgramUserStatus
  joinTime: Date
}

type Program {
  programUser: ProgramUser
}
```
What do you think?

**Comment by rosibaj** [comment]
@hlminh2000 That is not the same relationship.  Administrators are already added to the EGO program, which is what #189 is referring to.  In this ticket, the user has _not yet joined_ so has not yet been added to the EGO groups for that program, so even if you are invited as an Admin, if you have not yet accepted the you would not show up in that admin list.

**Comment by hlminh2000** [comment]
```graphql
enum ProgramUserRole {
  # whatever values here
}

enum ProgramUserStatus {
  # whatever values here
}

type ProgramUser {
  name: String
  email: String
  role: ProgramUserRole
  dacoApproved: Boolean
  status: ProgramUserStatus
  joinTime: Date
}

type Program {
  # whatever else that's there already
  programUsers: [ProgramUser]
  programAdmin: [ProgramUser] # <------------ this is a filtered
}
```
Would the above updated schema make sense then? The update being `programAdmin` is a filtered list of `ProgramUser` to those that have joined?

**Comment by joneubank** [comment]
@rosibaj does this address users that accepted invitations but have since left or been removed from teh program? I feel like they will be returned as an accepted invite by this service.

**Comment by joneubank** [comment]
Kevin clarified this functionality offline. It is properly checking user's status in ego before returning them in teh service. We are renaming the message object in the response to remove the confusion.

**Comment by rosibaj** [comment]
@alekspejovic Can you link the other status ticket to this one?

**Comment by alekspejovic** [comment]
@rosibaj added the status ticket as a dependency.
