### ISSUE TITLE
Need to update JoinProgram success response message

### ISSUE THREAD

**Issue by alekspejovic** [icgc-argo/program-service#123]
Currently the response message for Join Program is empty.  There is no indication of a success invitation.

Let's connect with @joneubank on what the best success response it: 

Proposal during sprint planning:
```
{
join_date: Date
}
````

**Comment by Buwujiu** [comment]
Decided to return `message User` as JoinProgramResponse.
```message User {
  google.protobuf.StringValue email = 1;
  google.protobuf.StringValue first_name = 2;
  google.protobuf.StringValue last_name = 3;
  UserRoleValue role = 4;
}```

**Comment by alekspejovic** [comment]
There should be an error thrown when the user does not exist in Ego. Currently, there is a bug in the implementation of InviteUser, where it is not properly creating a user in Ego. See ticket below :

https://github.com/icgc-argo/program-service/issues/132

When you try using JoinProgram, and pass in the invitationdID for the case above (where the user is not created), it gives you back a successful response. However, there is no user in Ego, and there is no users added to the program group. This should not indicate a successful response.

**Comment by alekspejovic** [comment]
Tested in QA after new changes - looks great! Thanks @Buwujiu
