### ISSUE TITLE
Create tables for countries , regions, and institutions

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/program-service#129]
Need to have tables for all of these entities:

- **List** Countries
- **List** Primary Site
- **List** Cancer Types
- **List** and **Add** Institutions
- **List** Regions

**Comment by rosibaj** [comment]
@joneubank @Buwujiu @alekspejovic Got this ticket on board so that we can talk about what is needed endpoint wise to meet this requirement!

**Comment by alekspejovic** [comment]
@Buwujiu  to propose an API for this.
