### ISSUE TITLE
Create Program: Initial Program Table fields 

### ISSUE THREAD

**Issue by alekspejovic** [icgc-argo/program-service#13]
On Program Creation :

**MUST be provided :**
- name
- shortname
- membershiptype
- commitmentDonors
- At least one country
- At least one cancer type
- Email and first/last name of at least one PI 

**Optionally :**
- Description
- Institutions

**System action on Program Creation :**
- submittedDonors and genomicDonors set to 0
- dateCreated, dateUpdated set to current date

*Spec Link* 
https://wiki.oicr.on.ca/display/icgcargotech/Program+Service+-+Backend#ProgramService-Backend-3.1.1.1program

**Comment by rosibaj** [comment]
Extending inplementation with https://github.com/icgc-argo/program-service/issues/28

**Comment by rosibaj** [comment]
Removed create admin from scope; will be done here: https://github.com/icgc-argo/program-service/issues/32

**Comment by Buwujiu** [comment]
Ticket is covered in PR #37, closing ticket.
