### ISSUE TITLE
Add the value "Multiple" to the list of Primary Sites & Cancer Types

### ISSUE THREAD

**Issue by alekspejovic** [icgc-argo/program-service#133]
The current data set can be found here :

https://wiki.oicr.on.ca/display/icgcargotech/Program+Service+-+Backend

We should add the value "Multiple" to both, to signify ARGO programs who are investigating multiple types of cancer.

**Comment by d8660091** [comment]
It's already multiple, nothing to do

**Comment by rosibaj** [comment]
@d8660091 I see `Multiple` as a value only in Cancer-Type in the create program form.  `primary sites` should also contain the value `Multiple`.  I will move back to In progress.

**Comment by d8660091** [comment]
@rosibaj Should multiple appear in institution?

**Comment by rosibaj** [comment]
@d8660091  no

**Comment by rosibaj** [comment]
tested- i can now see both
