### ISSUE TITLE
Invitation status logic needs to be updated 

### ISSUE THREAD

**Issue by alekspejovic** [icgc-argo/program-service#153]
We need to update the logic for invitation statuses in the join_program_invite table to make sure we are correctly displaying information about the state of a user's invitation within a program. 
Wiki: https://wiki.oicr.on.ca/display/icgcargotech/User+Registration 
**High level requirement** : There should only be ONE active pending invitation per user per program at a given time. 

There should be 5 possible statuses for an invitation: _PENDING, ACCEPTED, EXPIRED, REVOKED, INVALID._

* _PENDING_ -> The invitation has been sent to the user, has not yet been accepted by the user, and is not expired.
* _ACCEPTED_ -> The invitation has been sent to the user, and the user has accepted before the invitation has expired. Once a user has accepted an invitation for a selected program, they should not be able to receive any future invitations for that program (unless they are first removed from the program completely). 
* _EXPIRED_ -> The invitation has been sent to the user, but the user did not accept the invitation by the selected expiry date. It is possible to have an expired invitation, and then resend a new invitation to the user (the state should be kept as expired in this case). 
* _REVOKED_ -> The invitation has been sent to the user, but in the meantime, the program admin has chosen to revoke the invitation before the user has accepted. Also, for a user that has accepted an invitation for a program, but has since been removed from the program, then their invitation status should also be set to revoked. 
* _INVALID_ -> If a new invitation is sent while another invitation is in the PENDING state, the PENDING invitation should be set to invalid. 
 
New logic that needs to be implemented at the **_InviteUser_** endpoint:
- [x] Once an invitation is sent, we need to check if there is any existing invitations for the user for that program .
- [x] If there is an ACCEPTED invitation already, we should return an error saying that the user has already accepted the invitation to join that program.
- [x]  If there is a PENDING invitation, then that previous invitation should be set to INVALID. 
If a previous invitation is EXPIRED,REVOKED or INVALID, leave them as is. 

Logic which should be tested at the **_JoinProgram_** level:
 - [x] A user should only be able to accept an invitation in a PENDING state. Calling JoinProgram for an invitationId in any other state should return an error message. 

Logic which should be implemented for **_ListUsers_**:
- [x] Only the latest invitations should be retrieved for a user with multiple invitations. All REVOKED or INVALID invitations should not be retrieved.

**Comment by alekspejovic** [comment]
Hey @KevinFHartmann ,

I am seeing some weird errors on the UI from GraphQL when I try resending an invitation for a user or removing a user.

On attempt to resend and invitation that has "Invitation Expired" listed in the status, I get the following error. 

{"errors":[{"message":"6 ALREADY_EXISTS: Invitation was already accepted","locations":[{"line":2,"column":3}],"path":["inviteUser"],"extensions":{"code":"INTERNAL_SERVER_ERROR","exception":{"errors":[{"message":"6 ALREADY_EXISTS: Invitation was already accepted","locations":[],"path":["inviteUser"]}],"stacktrace":["Error: 6 ALREADY_EXISTS: Invitation was already accepted","    at new CombinedError (/usr/src/node_modules/graphql-tools/src/stitching/errors.ts:90:5)","    at Object.checkResultAndHandleErrors (/usr/src/node_modules/graphql-tools/src/stitching/errors.ts:111:11)","    at CheckResultAndHandleErrors.transformResult (/usr/src/node_modules/graphql-tools/src/transforms/CheckResultAndHandleErrors.ts:15:12)","    at /usr/src/node_modules/graphql-tools/src/transforms/transforms.ts:37:45","    at Array.reduce (<anonymous>)","    at applyResultTransforms (/usr/src/node_modules/graphql-tools/src/transforms/transforms.ts:35:21)","    at /usr/src/node_modules/graphql-tools/src/stitching/delegateToSchema.ts:104:12","    at step (/usr/src/node_modules/graphql-tools/dist/stitching/delegateToSchema.js:31:23)","    at Object.next (/usr/src/node_modules/graphql-tools/dist/stitching/delegateToSchema.js:12:53)","    at fulfilled (/usr/src/node_modules/graphql-tools/dist/stitching/delegateToSchema.js:3:58)"]}}}],"data":{"inviteUser":null},"extensions":{"tracing":{"version":1,"startTime":"2019-08-19T16:11:24.559Z","endTime":"2019-08-19T16:11:24.576Z","duration":16572650,"execution":{"resolvers":[{"path":["inviteUser"],"parentType":"Mutation","fieldName":"inviteUser","returnType":"String","startOffset":163819,"duration":16391555}]}}}}

On trying to Remove a user :
GraphQL response :
{"errors":[{"message":"3 INVALID_ARGUMENT: expiresAt=>must be a date in the present or in the future","locations":[{"line":2,"column":3}],"path":["removeUser"],"extensions":{"code":"INTERNAL_SERVER_ERROR","exception":{"errors":[{"message":"3 INVALID_ARGUMENT: expiresAt=>must be a date in the present or in the future","locations":[],"path":["removeUser"]}],"stacktrace":["Error: 3 INVALID_ARGUMENT: expiresAt=>must be a date in the present or in the future"," at new CombinedError (/usr/src/node_modules/graphql-tools/src/stitching/errors.ts:90:5)"," at Object.checkResultAndHandleErrors (/usr/src/node_modules/graphql-tools/src/stitching/errors.ts:111:11)"," at CheckResultAndHandleErrors.transformResult (/usr/src/node_modules/graphql-tools/src/transforms/CheckResultAndHandleErrors.ts:15:12)"," at /usr/src/node_modules/graphql-tools/src/transforms/transforms.ts:37:45"," at Array.reduce ()"," at applyResultTransforms (/usr/src/node_modules/graphql-tools/src/transforms/transforms.ts:35:21)"," at /usr/src/node_modules/graphql-tools/src/stitching/delegateToSchema.ts:104:12"," at step (/usr/src/node_modules/graphql-tools/dist/stitching/delegateToSchema.js:31:23)"," at Object.next (/usr/src/node_modules/graphql-tools/dist/stitching/delegateToSchema.js:12:53)"," at fulfilled (/usr/src/node_modules/graphql-tools/dist/stitching/delegateToSchema.js:3:58)"]}}}],"data":{"removeUser":null},"extensions":{"tracing":{"version":1,"startTime":"2019-08-19T16:07:26.600Z","endTime":"2019-08-19T16:07:26.634Z","duration":33697883,"execution":{"resolvers":[{"path":["removeUser"],"parentType":"Mutation","fieldName":"removeUser","returnType":"String","startOffset":616393,"duration":33058482}]}}}}

**Comment by rosibaj** [comment]
Error happens when removing a pending user:
![image](https://user-images.githubusercontent.com/15824252/63618991-860bfe80-c5bb-11e9-9714-c7af691cd7fc.png)
![image](https://user-images.githubusercontent.com/15824252/63619030-9cb25580-c5bb-11e9-8602-b98ed0e61bb1.png)

Gateway query:
```
{
  "operationName": "REMOVE_USER_MUTATION",
  "variables": {
    "userEmail": "rosi.bajari@oicr.on.ca",
    "programShortName": "AAAA-RO"
  },
  "query": "mutation REMOVE_USER_MUTATION($userEmail: String!, $programShortName: String!) {\n  removeUser(userEmail: $userEmail, programShortName: $programShortName)\n}\n"
}```

**Comment by rosibaj** [comment]
@KevinFHartmann is the error above for a pending user related to: https://github.com/icgc-argo/program-service/issues/210 ?

**Comment by rosibaj** [comment]
Closing as these issues have been resolved in QA environment! Thanks @KevinFHartmann !!
