### ISSUE TITLE
Can pollute ego in the case of bad emails

### ISSUE THREAD

**Issue by andricDu** [icgc-argo/program-service#160]
**Describe the bug**
Create Program accepts input with a bad user email, allowing for policies to be created, but not users which puts ego in an inconsistent state. 

**Steps To Reproduce**
1. Open up BloomRPC
2. Try to create a program with a bad email for the user
3. Get strange error

**Expected behaviour**
The program service should validate that the incoming user emails are of valid format. 

Potential solutions :
- Need to address the transactional failure mode

**Comment by alekspejovic** [comment]
Tested in QA - lgtm!
