### ISSUE TITLE
Add pre-recieve server side hook to detect non-pushed git submodules

### ISSUE THREAD

**Issue by rtisma** [icgc-argo/program-service#21]
Scenario
1. clone program service and initialize submodules
2. make a change to src/main/argo-proto submodule, commit and **NOT** push
3. add the new submodule commit to the main git repo (program-service) and commit, and push

on the remote side (i.e github), program service will be referencing a commit id of its submodule that is not present in github. any user that clones this commit of the program service (not neccessarily `master` and tries to initialize the submodules will get an error

Simple fix, is to add a pre-recieve hook, to catch this as early as possible. Here is an example
 https://gist.github.com/bagage/bdca3d4b66d43db7a5e3

The above script demonstrates some other issues with submodes and provides a solution to managing them. Although we have Jenkins to build (which should fail if these issues are present), branches that are not being merged into master (and therefore not sanitized by Jenkins) could suffer from these issues, wasting developer time in debugging or context switching. It would be nice to have something like this to catch the issue before its even pushed to github.

**Comment by alekspejovic** [comment]
- Create a new branch off of submodule
