### ISSUE TITLE
Update JWT format

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/program-service#228]
The ego jwt format has been updated. 

Make sure that the program service is responding to the correct scopes in the new jwt structure. 

Referencing: https://github.com/icgc-argo/program-service/pull/250 
A refactor should still take place in the future as the semantics of

public class EgoToken extends Context.User
are wrong. It should extend the Context or even more as the token could be making use of the aud field.

**Comment by rosibaj** [comment]
Closing as this work was completed in scope of another ticket.

**Comment by andricDu** [comment]
Deployed and tested in dev
