### ISSUE TITLE
List  Programs Users

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/program-service#23]
Get Program Users :

- Provide program ID
-  Retrieve a list of all users belonging to the Program (lookup the programEgoGroup table in program database to find all groups belonging to the program).
- In Ego, retrieve all the users from each of the above groups **EXCEPT** the **BANNED** group

**Comment by alekspejovic** [comment]
- Depends on reviewing the permissions for Ego.

**Comment by alekspejovic** [comment]
Can we please make sure that all the specs in the ticket are implemented before closing?

I opened this new issue for excluding banned users : 
https://app.zenhub.com/workspaces/argo-5c8c8637777e5f767e486217/issues/icgc-argo/program-service/93.
