### ISSUE TITLE
Remove `A.A.Kharkevich Institute of Information Transmission Problems` from list of Institutions

### ISSUE THREAD

**Issue by christinayung** [icgc-argo/program-service#237]
For demo purpose, please remove this institute as it's glaring as the first line

![image.png](https://images.zenhubusercontent.com/5bbe9c22307bc60241e3aa93/3079fc21-d437-4bc8-847c-a8cc5e45d471)

**Comment by Buwujiu** [comment]
Institution is removed from QA DB for demo.
