### ISSUE TITLE
Update programs 

### ISSUE THREAD

**Issue by alekspejovic** [icgc-argo/program-service#24]
We need to have a method for updating a program as part of the program-service:

This would involve:
- [ ] updating anyone of the fields in the program table, 
- [ ] or a program's cancer types/primary sites relationship
- [ ] Authorization for this method is strictly for a DCC admin. 
- [ ] All of the fields are mutable (except for id). 

What needs  to happen for us to be able to implement this method.

- Do we need any changes to the protobufs file?
- Does this need to be split up into multiple tickets if other changes are needed?

**Comment by Buwujiu** [comment]
This ticket is for updating the basic Program information, will add additional tickets for add/remove cancer_type and primary_site.

**Comment by rosibaj** [comment]
will be merged today - closing in sprint
