### ISSUE TITLE
Only one of Jenkins pr-merge and branch should be triggered for build.

### ISSUE THREAD

**Issue by Buwujiu** [icgc-argo/program-service#26]
![Screen Shot 2019-04-22 at 10.31.17 AM.png](https://images.zenhubusercontent.com/5c9a3377f234b2000189633c/5776ec1f-fdf1-4875-9ce4-7ae76660aea3)

**Comment by rosibaj** [comment]
@Buwujiu @blabadi is this still a valid ticket?

**Comment by Buwujiu** [comment]
Most likely not valid anymore.
