### ISSUE TITLE
Create Program - Initialize Ego Groups

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/program-service#28]
Specs Link: https://wiki.oicr.on.ca/pages/viewpage.action?pageId=110627486#PermissionsManagement&IntegrationtoEgo-CreatingaProgram

When a program is created, the program groups need to be initialized in Ego at the time of creation.  Each time a new program is created: 

- [ ]  Create 2 policies in Ego in the following format: 
-- PROGRAM-[program.shortname] 
-- PROGRAM-DATA-[program.shortname]

- [ ] Create 5 groups in Ego in the following format: [program.shortname]-[role].  For example, if the shortName is 'ProgramA' then 'ProgramA-Admins' , 'ProgramA-Members', 'ProgramA-Collaborators'.

The the roles and corresponding permission sets for ARGO should be stored as `environment variables` that can reference the role to the permission set.  The end results should be 5 groups per program like so:

- PROGRAM-[program.shortname]-Admins with the mask ADMIN
- PROGRAM-[program.shortname]-Collaborator with the masks [program.shortname].WRITE,  PROGRAM-DATA-[program.shortname]-DATA.WRITE
- PROGRAM-[program.shortname]-Submitter with the masks [program.shortname].READ,  PROGRAM-DATA-[program.shortname].WRITE
- PROGRAM-[program.shortname]-Collaborator with the mask [program.shortname].READ,    PROGRAM-DATA[program.shortname].READ 
- PROGRAM-[program.shortname]-Banned with the masks [program.shortname].DENY,    PROGRAM-DATA-[program.shortname].DENY

**Comment by KevinFHartmann** [comment]
Implemented as part of
