### ISSUE TITLE
Import Programs from ICGC

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/program-service#286]
https://wiki.oicr.on.ca/display/icgcargotech/Initializing+the+ICGC+dataset+in+ARGO

**Comment by blabadi** [comment]
Just something that popped while me and @rosibaj where discussing the similar ticket for clinical, the ego groups for the 4 carried over programs to argo, also need to be created

**Comment by rosibaj** [comment]
thanks @blabadi - that is noted in the wiki number number 1) now as well!

**Comment by rosibaj** [comment]
tested by activating PACA-CA in production with @rtisma - Program Activation was successful and instructions recorded on the wiki : 
https://wiki.oicr.on.ca/display/icgcargotech/Activating+ICGC+Programs+in+ARGO
