### ISSUE TITLE
🐛  Invite email does not contain subject and short title

### ISSUE THREAD

**Issue by rtisma** [icgc-argo/program-service#308]
![Screenshot from 2020-03-02 13-47-02](https://user-images.githubusercontent.com/942951/75707147-681b0700-5c8c-11ea-9a40-af2512b97f35.png)
![Screenshot from 2020-03-02 13-47-23](https://user-images.githubusercontent.com/942951/75707154-694c3400-5c8c-11ea-9803-6b9396f5f759.png)

Email invite - we should change the the subject to 

Subject: ** You have been invited to join an ICGC ARGO program**

**Comment by blabadi** [comment]
I've also addressed the links issue here (from https://github.com/icgc-argo/platform-ui/issues/1069) : 
Email invite:

    open email in browser link should open the html email in the browser
    "DACO approval" should link to: https://icgc.org/daco
    "check out our documentation" in body copy link to: https://docs.icgc-argo.org/
    "The ARGO Data Platform team" should link to https://platform.icgc-argo.org/
    Email footer: "Contact" should link to: https://platform.icgc-argo.org/contact
    Email footer: "Documentation" should link to: https://docs.icgc-argo.org/
    Email footer: "Privacy Policy" should link to: https://platform.icgc-argo.org/privacy

**Comment by blabadi** [comment]
PR https://github.com/icgc-argo/program-service/pull/309

**Comment by blabadi** [comment]
tested on dev env and all looks good, working on deploying to QA now

![image.png](https://images.zenhubusercontent.com/5c99083bd2fde800015cf9fa/6cc35db3-4d33-4fc5-9c44-f29e4b4cd3ad)

**Comment by kcullion** [comment]
looks good to me in QA

**Comment by kcullion** [comment]
@blabadi I tested this in production and it works great. saw this in my gmail
<img width="815" alt="Screen Shot 2020-03-04 at 5 50 34 PM" src="https://user-images.githubusercontent.com/18424138/75930616-fa640c00-5e40-11ea-8448-803f2f1c644c.png">

and the links all work.

Do we close this ticket then?

**Comment by blabadi** [comment]
Yes please, @kcullion

**Comment by kcullion** [comment]
@blabadi it feels now like the tickets go through such a journey to get to the closed state haha

**Comment by blabadi** [comment]
Yeah they may start having birthdays @kcullion
