### ISSUE TITLE
Program Invite Email: text and footer link change

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/program-service#316]
- [ ] Please update the body copy to read:
**Joining a program means you will have permission to access, submit or download program data, depending on your program role and DACO access.** 

- [ ] Update the url for the privacy link to point to: https://www.icgc-argo.org/page/2/privacy

- [ ] also the `check our documentation` takes the user to the program access doc page.

Zeplin: https://zpl.io/Vqv9gLm

<img width="480" alt="Screen Shot 2020-03-26 at 3 24 38 PM" src="https://user-images.githubusercontent.com/18424138/77688132-f033ba00-6f75-11ea-861f-3469e2c01b6b.png">

**Comment by blabadi** [comment]
whoever deploys program service to production please check this PR: https://github.com/OICR/argo-infra/pull/168/files

**Comment by kcullion** [comment]
@rosibaj @blabadi did a test on QA. This looks good to me!

**Comment by rosibaj** [comment]
@blabadi just want to confirm since ticket is not moved, this should be in the QA column yes?

**Comment by rosibaj** [comment]
weird! i saw this in code review before! an error on my end.  please ignore comment above!

**Comment by blabadi** [comment]
it appears in different locations in different zenhub boards

**Comment by rosibaj** [comment]
changes verified on prod
