### ISSUE TITLE
Update Email invite text

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/program-service#323]
- [ ] In the email invitation, please change this sentence
Joining a program means you will have permission to access program data, provided that you also have DACO approval. 
 - [ ] Change the privacy link in the email footer to also link to the same link the portal does.

To:
**Joining a program means you will have permission to access, submit or download program data, depending on your program role.**

Zeplin: https://zpl.io/Vqv9gLm
<img width="697" alt="Screen Shot 2020-03-18 at 4 53 23 PM" src="https://user-images.githubusercontent.com/18424138/77007075-f2749380-6939-11ea-9706-7d6245518c7b.png">

NOTE: Please do not implement the "view this in browser" in the example image above.  That was removed and is an old artifact of the mockup.

**Comment by rosibaj** [comment]
@kcullion we also removed view this email in your browser link correct? i see it in the mockup example still?

**Comment by kcullion** [comment]
@rosibaj yes sorry. Bashar removed that, just forgot to remove from my mock

**Comment by rosibaj** [comment]
it has been moved.

**Comment by kcullion** [comment]
closing this - duplicate.
This ticket has the correct content: https://github.com/icgc-argo/program-service/issues/316
