### ISSUE TITLE
Beta-Feedback: Add Program ID to email

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/program-service#327]
Beta testers are confused as to where they find their program_id.

- [ ] To help with this, please add a reference to their Program ID in the welcome email

Zeplin: https://zpl.io/Vqv9gLm

<img width="639" alt="2020-04-27_1018" src="https://user-images.githubusercontent.com/18424138/80382630-7e020e00-8870-11ea-9a5c-41679d5ae245.png">

- [ ] Also, please update this link to the new url: /docs/submission/managing-program-access

<img width="650" alt="2020-05-28_1710" src="https://user-images.githubusercontent.com/18424138/83194262-5c61a400-a106-11ea-8d3b-f4494598659f.png">

**Comment by rosibaj** [comment]
@kcullion can you double check this one?  i think it might be done.

**Comment by kcullion** [comment]
@rosibaj just checked in the email from mailhog and it hasn't been added yet
<img width="732" alt="Screen Shot 2020-05-21 at 4 18 23 PM" src="https://user-images.githubusercontent.com/18424138/82602244-c74b3200-9b7e-11ea-80f0-865eb672a538.png">

**Comment by kcullion** [comment]
Like I think we should say Program Name and Program ID - they were asking what "Program id" is

**Comment by rosibaj** [comment]
thanks for confirming!

**Comment by blabadi** [comment]
I just want to point something, the text of the program name, id, role, email looks like hyperlinks because they are blue

**Comment by kcullion** [comment]
thanks @blabadi the links are purple and underlined..but you can change this to the colour of the field titles if you want (dark blue). I can see how they may look like links!

**Comment by blabadi** [comment]
no if you think it's fine I'm good too

here is the local testing result:
![image.png](https://images.zenhubusercontent.com/5c99083bd2fde800015cf9fa/bd6c8412-9a6d-4758-9f1a-6706afb214bc)

**Comment by kcullion** [comment]
looks good to me @blabadi I'll test once in QA

**Comment by rosibaj** [comment]
Any reason i see on two lines in QA mailhog @blabadi ?

![image](https://user-images.githubusercontent.com/15824252/83458890-54b93c80-a431-11ea-8362-2c268b88a344.png)

**Comment by kcullion** [comment]
@blabadi I think the first table column needs a width set (width:120px worked for me)...then a long program name will wrap in the second cell correctly like:
<img width="650" alt="Screen Shot 2020-06-02 at 9 48 35 AM" src="https://user-images.githubusercontent.com/18424138/83527843-5547e680-a4b6-11ea-8b69-60b13f80d3c7.png">

**Comment by blabadi** [comment]
I'll open another ticket to handle the spacing if this passed QA, please move it forward

**Comment by rosibaj** [comment]
@blabadi the rest of this is fine - can you just comment the ticket here?  Minh is deploying ui/gateway right now but maybe you can deploy this change later?

**Comment by rosibaj** [comment]
verified on production.  thanks @blabadi !
