### ISSUE TITLE
🐛 email program info table has wrapping issue

### ISSUE THREAD

**Issue by blabadi** [icgc-argo/program-service#333]
## Describe the bug

![image](https://user-images.githubusercontent.com/8655252/83661539-446da280-a594-11ea-972a-51e8d675e071.png)

**Comment by blabadi** [comment]
local test result : 
![image](https://user-images.githubusercontent.com/8655252/83662610-bd212e80-a595-11ea-8105-598cf15ec707.png)

**Comment by blabadi** [comment]
QA test result:
![image.png](https://images.zenhubusercontent.com/5c99083bd2fde800015cf9fa/b384b4e0-56ea-4eef-a8f6-cec67ee17463)

**Comment by rosibaj** [comment]
verified on production as well - thank you @blabadi !!!
