### ISSUE TITLE
Include program membership type in user scope: Create Program 

### ISSUE THREAD

**Issue by hlminh2000** [icgc-argo/program-service#337]
needed as part of this: https://wiki.oicr.on.ca/display/icgcargotech/Program+Membership+Metadata+Access+Control

## Detailed Description
1. The service's startup flow should be updated to sync up ego's group scopes with the associated program's member ship. After the the initialization is complete exits, the following must be true:

    - `PROGRAMMEMBERSHIP-FULL.read` exists in all **and only** ego user groups for programs with `FULL` membership who are also admins and data submitters
    - `PROGRAMMEMBERSHIP-ASSOCIATE.read` exists in all **and only** ego user groups for programs with `ASSOCIATE` membership who are also admins and data submitters

   Requirements:

    - This process should be idempotent so that future deployments of the application does not fail
    - should be feature flagged so we can turn it off the behavior later
    - TDD with test to:
      - confirm results
      - confirm re-run scenario

1. `CreateProgram` rpc method needs to be updated to do the same thing as above for one program only.

## Exit Criteria 
Test plan: Make a full membership program, check a Program admins scopes in the JWT and see the full membership scope.

**Comment by rosibaj** [comment]
Tested in QA environemnt - can see the scorrect policy applied in ego and in jwt when i  login as different users 

thanks so much @Buwujiu!!!!!!!!
