### ISSUE TITLE
Update a User

### ISSUE THREAD

**Issue by alekspejovic** [icgc-argo/program-service#34]
We need to have a method for updating a user as part of a program:

- [ ] User should exist in Ego.
- [ ] Accepts the user's uuid , and new role (optional)
- [ ] Update their role in a program to the new role . This is done by removing and adding them to the correct group in Ego (by doing a lookup of their role in the programEgoGroup table).

**Comment by rosibaj** [comment]
@alekspejovic @Buwujiu  

Tested this and the update user works!

2 questions: 
1) on update user, why do we need program id and shortname both?
2) when i add a garbage role code (`55` or `11`) i get a success and still get assigned collaborator status.  Should this throw an error instead?

**Comment by alekspejovic** [comment]
Created new ticket for point #2 above :

https://github.com/icgc-argo/program-service/issues/110.
