### ISSUE TITLE
🐛 Join a Program Email - broken link and make year dynamic in footer

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/program-service#370]
## Describe the bug

- [ ] The documentation link in the Join Invitation leads to a "page not found". It should go to this page: https://docs.icgc-argo.org/docs/submission/managing-program-access 
- [ ] Let's make the year in the email footer dynamic so it reports the current year. This is consistent with the icgc-argo website.

![image](https://user-images.githubusercontent.com/18424138/142463846-bce0bb6c-d1f1-4e36-9d4a-c5b8079bb1c9.png)

**Comment by blabadi** [comment]
transferred the issue to program service

**Comment by kcullion** [comment]
tested in QA. The link and footer are updated! thanks @blabadi 
![image](https://user-images.githubusercontent.com/18424138/145890170-c6980364-f620-4aef-94dc-54e888c00eb8.png)
