### ISSUE TITLE
Add a new REST Endpoint for Getting Public Program Data

### ISSUE THREAD

**Issue by Buwujiu** [icgc-argo/program-service#379]
## Detailed Description
As a part of requirement of program entity page(https://wiki.oicr.on.ca/display/icgcargotech/Program+Entity+Page), we want to show a basic program summary. Currently all the program service API endpoints are behind Auth, in order to support the public facing program entity page, we should make a new REST endpoint for getting public program data.

## Possible Implementation
1. Create a new REST endpoint that returns these data fields without Auth:

1. program shortname
2. Description 
3. Name
4. Website
5. Institutions
6. Countries 
7. Processing Regions
8. Cancer types
9. Primary sites

- Basic Error Handling:
  - should return 404 when querying a non-existent program.
## Exit Criteria
Users should be able to query the new REST endpoint without JWT and get back the data fields listed above.

**Comment by Buwujiu** [comment]
status update: PR is merged to dev,  but there is no http networking setup for program service, Azher is working on helm chart updates and then some changes in kubernetes ingress rules.

**Comment by Azher2Ali** [comment]
DEV testing is completed.

**Comment by Azher2Ali** [comment]
Moving to QA testing

**Comment by Buwujiu** [comment]
https://program-service.qa.argo.cancercollaboratory.org/swagger-ui/index.html#/public-program-controller/getPublicProgramDataUsingGET

**Comment by Buwujiu** [comment]
small fee![Screen Shot 2023-03-08 at 10.47.13 AM.png](https://images.zenhubusercontent.com/5c9a3377f234b2000189633c/983841f7-0ff7-47cf-ad0e-e744677ae846)dback:

**Comment by Buwujiu** [comment]
Tested in QA, working as expected!

**Comment by Buwujiu** [comment]
@Azher2Ali Please add a version label to this ticket, thank you!

**Comment by Azher2Ali** [comment]
Have added the version label, as requested.
