### ISSUE TITLE
Add New REST Endpoint to Get List of Programs

### ISSUE THREAD

**Issue by joneubank** [icgc-argo/program-service#381]
## Detailed Description
New REST endpoint to access list of programs registered, returning an array of program short names.

## Possible Implementation
Add to the `/public` route controller, should return an array of strings containing all program short names that are registered. No authorization restrictions.

Please also add to Swagger.

**Comment by Azher2Ali** [comment]
Moving it to QA testing

**Comment by Buwujiu** [comment]
https://program-service.qa.argo.cancercollaboratory.org/swagger-ui/index.html#/public-program-controller/getPublicProgramDataUsingGET

**Comment by Buwujiu** [comment]
Tested in QA, working as expected!
