### ISSUE TITLE
Add tests for  entity association

### ISSUE THREAD

**Issue by rtisma** [icgc-argo/program-service#58]
currently, jpa entities are not being synced:

```java
programCancer.setProgram(program);
programCancer.setCancer(cancer);
program.getProgramCancers().add(programCancer);
cancer.getProgramCancers().add(programCancer);
```
All entities that have children have to be tested for associating and disassociating children. For example, Program and EgoGroups share a OneToMany. There needs to be tests to ensure an association happens. Can be done by mocking (prefered) or by depending on hibernate and comparing output (not-preferred)

**Comment by Buwujiu** [comment]
This is done under ticket #120 - fix update program.
