### ISSUE TITLE
List Users method should also return user's role in response 

### ISSUE THREAD

**Issue by alekspejovic** [icgc-argo/program-service#86]
Currently the response looks like this : 

{
  "users": [
    {
      "id": {
        "value": "a5ccd95f-7ee4-446f-a844-ccc6f5d437c1"
      },
      "email": {
        "value": "test@test.com"
      },
      "first_name": {
        "value": "Aleksandra"
      },
      "last_name": {
        "value": "Pejovic"
      }
    }
  ]
}

The user's role in the program should also be provided in the response.

**Comment by rosibaj** [comment]
Tested - the role is now listed in the user response!
