### ISSUE TITLE
Clean up protobufs definitions for Program. Make cancer_type and primary_sites protobuf enums. Fix the corresponding database tables. 

### ISSUE THREAD

**Issue by KevinFHartmann** [icgc-argo/program-service#97]
Our protocol buffers shouldn't have certain fields in the Program definition, as the comments in the file confirm.

We also need to create enumerations for our cancer_type and primary_site data types. This will
require us to modify those database tables.

Hopefully, we can then go on to finally get the tables working right in Hibernate.

**Comment by rosibaj** [comment]
@Buwujiu @KevinFHartmann Can we please sync the implementation with #87 as we saw a little bit of difference in the implementations?
